services:
  lunchsplitter:
    image: lunchsplitter:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - sqlserver
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - .env
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
